export const Constants = {
    CARGILL_GREEN_COLOR: '#658D1B',
    CARGILL_BLUE_COLOR: '#005F86',
    CARGILL_YELLOW_COLOR: '#DAAA00',
    CARGILL_RED_COLOR: '#9E2A2F',
    CARGILL_GRAY_COLOR: '#E5E5E5',
    CARGILL_DARKGRAY_COLOR: '#333333',
    DEFAULT_BLACK: '#212121',
    DEFAULT_WHITE: '#FFF',

}